---
- name: Ensure PostgreSQL is installed and up-to-date.
  apt:
    name: '{{ item }}'
    update_cache: 'yes'
    state: 'latest'
  with_items:
    - 'postgresql'
    - 'postgresql-contrib' # For extensions, e.g. unaccent and pg_trgm
    - 'python3-psycopg2'    # For management by ansible
  become: true

- name: Ensure PostgreSQL is running.
  service:
    name: 'postgresql'
    state: 'started'
    enabled: true
  become: true

- name: Create PostgreSQL database.
  postgresql_db:
    name: '{{ postgresql_database }}'
    state: 'present'
  become: true
  become_user: 'postgres'

- name: Create PostgreSQL extensions.
  postgresql_ext:
    db: '{{ postgresql_database }}'
    name: '{{ item }}'
  with_items: '{{ postgresql_extensions }}'
  become: true
  become_user: 'postgres'

- name: Create PostgreSQL user.
  postgresql_user:
    name: '{{ postgresql_user }}'
    db: '{{ postgresql_database }}'
    password: '{{ postgresql_password|default(omit) }}'
    priv: 'ALL'
    state: 'present'
  become: true
  become_user: 'postgres'
