---
- name: Ensure supervisor is installed and up-to-date.
  apt:
    name: 'supervisor'
    state: 'latest'
  become: true

- name: Ensure supervisor configuration is up-to-date.
  template:
    src: 'etc/supervisor/conf.d/celery.conf.j2'
    dest: '/etc/supervisor/conf.d/{{ celery_app_module }}_celery.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
  become: true

- name: Run Celery.
  supervisorctl:
    name: '{{ celery_name }}'
    state: present
  become: true
  when: start

- name: Run Celery beat.
  supervisorctl:
    name: '{{ celery_beat_name }}'
    state: present
  become: true
  when: celery_beat
