---
- name: Ensure static files directory is present.
  file:
    owner: '{{ mangaki_sync_user }}'
    group: '{{ mangaki_sync_group }}'
    mode: 'u=rwx,g=rx,o=rx'
    path: '{{ mangaki_sync_static_root }}'
    state: 'directory'
    recurse: true
  become: true

- name: Collect static files.
  shell: '{{ mangaki_sync_manage }} collectstatic --no-input'
  environment: '{{ mangaki_sync_env }}'
  become: true
  become_user: '{{ mangaki_sync_user }}'
  run_once: true
  when: 'mangaki_sync_collectstatic|bool'
  tags: action

- name: Migrate database.
  shell: '{{ mangaki_sync_manage }} migrate'
  environment: '{{ mangaki_sync_env }}'
  become: true
  become_user: '{{ mangaki_sync_user }}'
  run_once: true
  when: 'mangaki_sync_migrate|bool'
  tags: action

- name: Compile locale messages.
  shell: '{{ mangaki_sync_manage }} compilemessages'
  environment: '{{ mangaki_sync_env }}'
  become: true
  become_user: '{{ mangaki_sync_user }}'
  run_once: true
  when: 'mangaki_sync_compilemessages|bool'
  tags: action

- block:
  - name: Copy fixture to remote host.
    copy:
      src: '{{ mangaki_sync_load_seed_path }}'
      dest: '{{ mangaki_sync_home }}/seed.json'
      owner: '{{ mangaki_sync_user }}'
      group: '{{ mangaki_sync_group }}'
      mode: '0644'

  - name: Load seed data.
    shell: '{{ mangaki_sync_manage }} loaddata {{ mangaki_sync_home }}/seed.json'
    environment: '{{ mangaki_sync_env }}'

  when: 'mangaki_sync_load_seed|bool'
  tags: action
  become: true
  become_user: '{{ mangaki_sync_user }}'
  run_once: true
