---
- name: Ensure site is available.
  template:
    src: 'etc/nginx/sites-available/default.conf.j2'
    dest: '/etc/nginx/sites-available/{{ nginx_site_name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - Test and reload nginx.
  become: true

- name: Ensure site is correctly enabled or disabled.
  file:
    src: '/etc/nginx/sites-available/{{ nginx_site_name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ nginx_site_name}}.conf'
    state: '{{ nginx_site_enabled|ternary("link", "absent") }}'
  notify:
    - Test and reload nginx.
  become: true

- name: Ensure site root has at least read permissions
  file:
    mode: 'o+rx'
    path: '{{ nginx_site_root }}'
  become: true
